### ISSUE TITLE
Authorising without Dropbox app does not persist token

### ISSUE THREAD

**Issue by lukestringer90** [dropbox/SwiftyDropbox#115]
When `authorizeFromController(_, controller:, openURL:)` is called and the Dropbox app is not installed (like on the simulator), a modal web view is shown to input a username and password. This is fine, and will obtain a token to use in subsequent web calls. However the token is not persisted, and so when launching the app again a user has to log in again. 

I've noticed this in version 3.3.1, and didn't seem to be a problem in 3.1.0. [This project on the feature/swift-2.3 branch](https://github.com/lukestringer90/DropboxClient/pull/1) replicates this problem if run on the simulator.

I am unsure whether I am using the SDK wrong (did something change between 3.1.0 and 3.3.1?) or I have uncovered a bug.

**Comment by timdeng2324** [comment]
Did the `authorizeFromController()` function change in this new version? The old function prototype just took `controller`. What do we put for all the new parameters?

**Comment by greg-db** [comment]
Thanks for the report @lukestringer90 , we'll look into it.

@timdeng2324 yes, `authorizeFromController` did change. We'll be updating the readme accordingly soon.

**Comment by sportlabsMike** [comment]
Hi @lukestringer90 

I found the same and am doing the following at the moment. Don't know if it's the best solution but it works:

```
let openUrl : NSURL -> Void = { url in

                if let authResult = Dropbox.handleRedirectURL(url) {
                    switch authResult {
                    case .Success(let token):
                        print("Success! User is logged into Dropbox with token: \(token)")
                    case .Error(let error, let description):
                        print("Error \(error): \(description)")
                    case .Cancel:
                        print("User cancelled")
                    }
                }
                
                return
            }

Dropbox.authorizeFromController(UIApplication.sharedApplication(), controller: self, openURL: openUrl, browserAuth: false)
```

**Comment by scobbe** [comment]
Tutorial is updated now with the new `authorizeFromController` interface (which changed to be app extension safe).

As far as the failure of the access token to persist on iOS, this looks like a bug with the Simulator: https://forums.developer.apple.com/message/170381#170381. 

To get around this as a temporary fix (for the Simulator environment), you should got to <YOUR_PROJECT> > Capabilities > Keychain Sharing > ON.

This should fix the issue until Apple releases an Xcode update. Let me know if this works for you.

**Comment by lukestringer90** [comment]
@greg-db Thanks for your reply. I've updated to version 4.0.1 and Swift 3.0 and the problem still persists.

@scobbe Thanks, this solved my problem. I'll try turning Keychain Sharing off in the next version of Xcode and let you know if Apple fixes the issue.
