### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by rhwood** [dropbox/SwiftyDropbox#122]
Please include a Package.swift so the Swift Package Manager can be used to import this.

**Comment by greg-db** [comment]
Thanks for the request!

**Comment by scobbe** [comment]
This should be fixed by 67de737. Let me know if you have any issues using the Swift PM with SwiftyDropbox.

**Comment by rolandleth** [comment]
Hey @scobbe,

I added this to the `Packages` file:

```
.Package(url: "https://github.com/dropbox/SwiftyDropbox", majorVersion: 4) 
// Tried with .git as well, but I don't know the difference between them
```

it resolves to the latest `4.1.1`, then resolves Alamofire to `4.0.0`, then it throws an error:

```
error: the package has an unsupported layout, unexpected source file(s) found: 
<all paths to test files, located in ./Packages/Alamofire-4.0.0/Tests>
fix: move the file(s) inside a module
```

Is there anything I can do to make it work? I tried adding this folder to the `excludes` array, but the problem persists.

Thank you!
